# Generated by Django 4.2.5 on 2023-10-30 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="biography",
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
