# Generated by Django 4.2.5 on 2023-11-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="documents",
            field=models.FileField(upload_to="documents"),
        ),
    ]
