# Generated by Django 4.2.5 on 2023-11-07 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profilepage", "0002_alter_studentprofile_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="mentor",
            name="documents",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="documents"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mentor",
            name="labname",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mentor",
            name="profile_pic",
            field=models.ImageField(default="default.png", upload_to="profile_pics"),
        ),
        migrations.AddField(
            model_name="mentor",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
