# Generated by Django 4.2.5 on 2023-11-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0003_alter_studentprofile_picture_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="document_name",
            field=models.CharField(default="none", max_length=255),
        ),
    ]
