# Generated by Django 4.2.5 on 2023-11-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_student_biography_student_course'),
        ('profilepage', '0007_alter_studentprofile_gpa'),
    ]

    operations = [
    ]
