# Generated by Django 4.2.5 on 2023-12-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0008_alter_studentprofile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='document_url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
