# Generated by Django 4.2.5 on 2023-12-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0009_studentprofile_document_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='background',
        ),
    ]
