# Generated by Django 4.2.6 on 2023-11-01 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gpa', models.IntegerField(default=0)),
                ('documents', models.IntegerField(default=0)),
                ('skill', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('biography', models.CharField(max_length=500)),
                ('background', models.CharField(choices=[('S', 'Student'), ('M', 'Mentor')], max_length=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
