# Generated by Django 4.2.5 on 2023-11-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='document_name',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='matched_by', to='profilepage.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='picture_name',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
