# Generated by Django 4.2.5 on 2023-10-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="student",
        ),
    ]
