# Generated by Django 4.2.5 on 2023-10-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="student",
            new_name="Skill",
        ),
    ]
