# Generated by Django 4.2.5 on 2023-10-25 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0002_rename_student_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="skill",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
