# Generated by Django 4.2.5 on 2023-10-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0003_skill_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="lastname",
        ),
    ]
