# Generated by Django 4.2.5 on 2023-11-07 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "profilepage",
            "0003_mentor_date_created_mentor_documents_mentor_labname_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="requiredcourse",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mentor",
            name="skill",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
