# Generated by Django 4.2.5 on 2023-11-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0004_mentor_requiredcourse_mentor_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mentor",
            old_name="user",
            new_name="user2",
        ),
    ]
