# Generated by Django 4.2.5 on 2023-10-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0002_skills_delete_student"),
        ("profilepage", "0004_remove_skill_firstname_remove_skill_lastname"),
    ]

    operations = []
