# Generated by Django 4.2.5 on 2023-12-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0005_studentprofile_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
