# Generated by Django 4.2.5 on 2023-11-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0006_studentprofile_labname_delete_mentor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="gpa",
            field=models.FloatField(default=0),
        ),
    ]
