# Generated by Django 4.2.5 on 2023-11-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0008_alter_studentprofile_biography_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="biography",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="course",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="gpa",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="skill",
            field=models.CharField(max_length=255),
        ),
    ]
